export const items = [
  {
    id: Math.random(),
    title: "وجبه فطار",
    description: "وصف الفطار",
    price: "100 ريال",
    category: "فطار",
    imgUrl: "1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه غدا",
    description: "وصف الفطار",
    price: "80 ريال",
    category: "غدا",
    imgUrl: "2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    description: "وصف الفطار",
    price: "40 ريال",
    category: "عشاء",
    imgUrl: "3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه غدا ممتاز",
    description: "وصف الفطار",
    price: "30 ريال",
    category: "غدا",
    imgUrl: "2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء درجه اولى",
    description: "وصف الفطار",
    price: "50 ريال",
    category: "عشاء",
    imgUrl: "3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه فطار",
    description: "وصف الفطار",
    price: "50 ريال",
    category: "فطار",
    imgUrl: "1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه سناك",
    description: "وصف الفطار",
    price: "50 ريال",
    category: "سناك",
    imgUrl: "1.jpg",
  },
];
